#!/bin/bash
set -e
INFILE="$1"
DIR=`dirname $INFILE`
BASENAME=`basename $INFILE .ins`
LLFILE="$DIR/${BASENAME}.ll"
BCFILE="$DIR/${BASENAME}.bc"

stack exec compile llvm "$INFILE" > $LLFILE
clang -emit-llvm -o "$BCFILE" -c "$LLFILE"
